/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI_Packages;

import java.awt.Button;
import javax.swing.JButton;
import Main.GameEngine;

/**
 *
 * @author Dell
 */
public class GUI_Interaction extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Interaction
     */
    private GameEngine mainEngine; 
    
    public GUI_Interaction(GameEngine gameEngine) {
        initComponents();
        
        mainEngine = gameEngine; 
        hideChoices(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSpeaker = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDialogue = new javax.swing.JTextArea();
        lblSprite = new javax.swing.JLabel();
        btnChoice1 = new javax.swing.JButton();
        btnChoice2 = new javax.swing.JButton();
        btnChoice3 = new javax.swing.JButton();
        btnChoice4 = new javax.swing.JButton();
        btnChoice5 = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblDay = new javax.swing.JLabel();
        lblLoc = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(560, 360));
        setPreferredSize(new java.awt.Dimension(560, 360));

        lblSpeaker.setText("character_name");

        txtDialogue.setEditable(false);
        txtDialogue.setColumns(20);
        txtDialogue.setRows(5);
        jScrollPane1.setViewportView(txtDialogue);

        lblSprite.setText("character_expression");

        btnChoice1.setText("choice 1");
        btnChoice1.addActionListener(this::btnChoice1ActionPerformed);

        btnChoice2.setText("choice 2");

        btnChoice3.setText("choice 3");

        btnChoice4.setText("choice 4");

        btnChoice5.setText("choice 5");

        btnNext.setText("next");
        btnNext.addActionListener(this::btnNextActionPerformed);

        lblDay.setText("day");

        lblLoc.setText("location");

        lblTime.setText("time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDay)
                        .addGap(126, 126, 126)
                        .addComponent(lblTime)
                        .addGap(139, 139, 139)
                        .addComponent(lblLoc))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnChoice1)
                                .addComponent(btnChoice2)
                                .addComponent(btnChoice3)
                                .addComponent(btnChoice4)
                                .addComponent(btnChoice5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSpeaker)
                                    .addGap(34, 34, 34)
                                    .addComponent(lblSprite)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNext))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(btnChoice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChoice2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChoice3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChoice4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChoice5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeaker)
                    .addComponent(lblSprite)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDay)
                    .addComponent(lblLoc)
                    .addComponent(lblTime))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnChoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoice1ActionPerformed
    
    boolean choicesVisibility = false; 
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        hideChoices(choicesVisibility);
        choicesVisibility = (choicesVisibility ? false : true);
//        getNextEvent(); 
    }//GEN-LAST:event_btnNextActionPerformed
    private void hideChoices(boolean vis){ 
        btnChoice1.setVisible(vis);
        btnChoice2.setVisible(vis);
        btnChoice3.setVisible(vis);
        btnChoice4.setVisible(vis);
        btnChoice5.setVisible(vis);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoice1;
    private javax.swing.JButton btnChoice2;
    private javax.swing.JButton btnChoice3;
    private javax.swing.JButton btnChoice4;
    private javax.swing.JButton btnChoice5;
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblLoc;
    private javax.swing.JLabel lblSpeaker;
    private javax.swing.JLabel lblSprite;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextArea txtDialogue;
    // End of variables declaration//GEN-END:variables
}


//    
//    private void setChoice(JButton btn, String txtBtnLabel){
//        btn.setVisible(true);
//        btn.setText(txtBtnLabel);
//    }
//    
//    private void setChoices(){
//        setChoice(btnChoice1, "testing");
//    }
//    
//    private void getNextEvent(){
//        if(mainEngine.setNextLine()==2) setChoices(); //write switch statement for choices UI
//        else hideChoices(false); 
//        lblSpeaker.setText(mainEngine.getSpeaker());
//        lblSprite.setText(mainEngine.getSprite());
//        txtDialogue.setText(mainEngine.getDialogue()); 
//    }
